USE [master]
GO

/****** Object:  Database [SwimmingPoolShop]    Script Date: 25.02.2025 21:12:25 ******/
DROP DATABASE [SwimmingPoolShop]
GO

/****** Object:  Database [SwimmingPoolShop]    Script Date: 25.02.2025 21:12:25 ******/
CREATE DATABASE [SwimmingPoolShop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SwimmingPoolShop', FILENAME = N'C:\Users\schne\SwimmingPoolShop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SwimmingPoolShop_log', FILENAME = N'C:\Users\schne\SwimmingPoolShop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SwimmingPoolShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SwimmingPoolShop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SwimmingPoolShop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SwimmingPoolShop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SwimmingPoolShop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SwimmingPoolShop] SET ARITHABORT OFF 
GO

ALTER DATABASE [SwimmingPoolShop] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [SwimmingPoolShop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SwimmingPoolShop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SwimmingPoolShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SwimmingPoolShop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SwimmingPoolShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SwimmingPoolShop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SwimmingPoolShop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SwimmingPoolShop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SwimmingPoolShop] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SwimmingPoolShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SwimmingPoolShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SwimmingPoolShop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SwimmingPoolShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SwimmingPoolShop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SwimmingPoolShop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SwimmingPoolShop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SwimmingPoolShop] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SwimmingPoolShop] SET  MULTI_USER 
GO

ALTER DATABASE [SwimmingPoolShop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SwimmingPoolShop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SwimmingPoolShop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SwimmingPoolShop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SwimmingPoolShop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SwimmingPoolShop] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SwimmingPoolShop] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SwimmingPoolShop] SET  READ_WRITE 
GO

